---
abstract: "minting profiles for FIBO[nacci]\r"
author:
  - 'G. Casati <fibo@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
  File::ShareDir::Install: 0.03
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-MintingProfile-Author-FIBO
requires:
  Dist::Zilla: 5.006
  Dist::Zilla::Plugin::AutoPrereqs: 0
  Dist::Zilla::Plugin::AutoVersion: 0
  Dist::Zilla::Plugin::PerlTidy: 0.13
  Dist::Zilla::Plugin::PkgVersion: 0
  Dist::Zilla::Plugin::Prereqs: 0
  Dist::Zilla::Plugin::ReadmeAnyFromPod: 0
  Dist::Zilla::PluginBundle::Basic: 0
  Moose: 2.1005
  MooseX::StrictConstructor: 0.19
version: 20131125
